BSData/wh40k

Imperium - Blood Angels.cat
Warhammer 40,000 8th Edition.gst

Updated files according to latest FAQ and errata.
Now all BA and FT characters are shown by default and hidden only if a
specific Chapter is selected. Closes #576 and hopefully everyone is
happy with it.

GST v13, BA v8

---

Imperium - Grey Knights.cat

There will be more later for smite showing, etc; but I'm getting on a plane...

fixing apothecary point level - Closes #605

---

Imperium - Blood Angels.cat

Land Speeder can now take two heavy flamers. Fixes #641.

Blood Angels v9

---

Aeldari - Craftworlds.cat

lots of FW units added, ref: #396

FW Units Added

---

Imperium - Blood Angels.cat
Warhammer 40,000 8th Edition.gst

Added master-crafted stalker bolt rifle profile to GST.
Added Master-crafted stalker bolt rifle entry to Blood Angels CAT.
Added Primaris Librarian and Primaris Captain entries to Blood Angels CAT.

Primaris HQ

---

Imperium - Adeptus Ministorum.cat

makes changes as per FAQ Index Imperium 2 Official Update Version 1.0 (06/2017)

Ad min faq #639

---

Aeldari - Craftworlds.cat

FW Complete

---

Aeldari - Craftworlds.cat

Aeldari Craftworlds FAQ Update

---

Aeldari - Drukhari.cat

Aeldari - Drukhari FAQ Update

---

Aeldari - Craftworlds.cat

Hornet Wargear Update

---

Imperium - Blood Angels.cat

Gabriel Seth got caught trying to steal a jump pack. Fixes #661.

BA v11 - Gabriel Seth fix

---

Orks.cat

Close #642
I also applied the FAQ updates.

Fix Forgeworld Damage Tables

---

Imperium - [FW] Death Korps of Krieg.cat

Adding Combat Engineers

---

Chaos - FW Renegade and Heretics.cat

Added Sniper and Set point on Malcador

Closes #637 & #652

---

Warhammer 40,000 8th Edition.gst

Closes #464. All weapon options now work properly and should be properly costed.

CSM Fallen fixes

---

Chaos - Daemons.cat
Warhammer 40,000 8th Edition.gst

- Fixes #737, #772, #765 
- Implements Psychic power picks and fixes Psyker abilities
- Refactors rules into abilities where appropriate.
- Main and IA FAQ changes
- Lots of other fixes for missing rules and/or weapon options.

CD Refactoring and fixes

---

Chaos - Chaos Space Marines.cat

CSM Lord can now take 2 plasma pistols.

Fix for #777

---

Imperium - Adeptus Ministorum.cat

AdMini: Immolator's Strom bolter changed from 4 pts to 2 as per FAQ, closes #751
--

AdMini: Immolator's Strom bolter changed from 4 pts to 2 as per FAQ, closes  #751

---

Chaos - Chaos Space Marines.cat

Fixes #797 - Changed implementation of Cultists to work better.

Fix for #797

---

Aeldari - Craftworlds.cat
Aeldari - FW Corsairs.cat

Forgeworld FAQ Added to Aeldari CATs

Forgeworld FAQ Added to Aeldari CATs

---

T'au Empire.cat

FW Tau errata

---

Chaos - Daemons.cat

Corrected cost for Burning Chariot.

Fixes #822

---

Chaos - Chaos Space Marines.cat

Fixed Chosen Champion points value

Fixes #848

---

Chaos - Chaos Space Marines.cat

Berzerkers can now dual wield chainaxes.

Fixes #860

---

Chaos - Chaos Space Marines.cat

Fixes #865

---

Chaos - Thousand Sons.cat

- Fixes #880
- Fixes #881
- Added Psychic Powers to all Sorcerers
- Fixed typo on Scarab Occults

1KSons Fixes

---

Chaos - Chaos Space Marines.cat

Price corrected for Berzerkers with Plasma pistol

Fixes #897

---

Chaos - Chaos Space Marines.cat

Fixes #902 - Made all berzerkers (except plasma pistol) collective.

Berzerkers are now tidy

---

Chaos - Daemons.cat

Burning Chariot is no longer Elites and Heavy Support

Fixes #492

---

Chaos - FW Renegade and Heretics.cat

updated with FAQ units and misc keywords for units

Closes #815 Closes #909 Closes #912 Closes #911 Closes #896

---

Chaos - Chaos Space Marines.cat
Chaos - Daemons.cat
Chaos - Thousand Sons.cat
Warhammer 40,000 8th Edition.gst

Index Chaos FAQ 1.1 Changes

---

Aeldari - Craftworlds.cat
Imperium - Space Wolves.cat

Aeldari FAQ & Space Wolf Updates

---

Chaos - Questor Traitoris.cat
Chaos - Titanicus Traitoris.cat

Questor and Titanicus Traitorous fixes for typos, weapon choice and some refactoring.

Chaos Lords of War

---

Chaos - Chaos Space Marines.cat

Noise Marine champ strength fix

---

Chaos - FW Renegade and Heretics.cat

been moving things to shared selections, fixed group selections, been moving group selections to shared, reached Disciple squad will continue when time allows

tidying up and working on #964

---

Imperium - Grey Knights.cat

fixing doomglaive dreadnought and lib in term armor
Verified strike teams are still good even with incinerator changes

Closes #977

---

Chaos - FW Renegade and Heretics.cat

Reworked all Imperial Armour - Index - Astra Militarum entries, for a more generic way

Closes #982 Closes 962

---

Chaos - FW Renegade and Heretics.cat

should have saved the Command squad bug fix this time

Face Palm Heavy weapon style

---

Chaos - Chaos Space Marines.cat

Fixes #990 - Corrected proifile for twin heavy flamer on Defiler

Fixes #990

---

Chaos - Chaos Space Marines.cat
Chaos - FW Heretic Astartes.cat

Chaos fixes 20170801

---

Imperium - Grey Knights.cat

Closes #1078

---

Chaos - FW Renegade and Heretics.cat

Corrected Militia, Command and Disciple squads to comly with BSData guidelines, corrected points in HW-Squad and removed max 1 from enforcer

Closes #993 Closes #1085

---

Chaos - Chaos Space Marines.cat
Chaos - Daemons.cat
Chaos - Thousand Sons.cat

- Fixes #1074 - Chaos Lord can now have a combi-bolter.
- Fixes #1077 - Chosen w/ weapon option can take a plasma pistol
- Fixes #1087 - Fixed cost for Burning Chariot Horrors
- Fixes #1088 - Fixed PL issue with Tzaangors
- Minor changes in Thousand Sons

Chaos fixes 20170803

---

Chaos - Chaos Space Marines.cat

Fixes #1105 - Corrected Plague Marine PL cost

Chaos Fixes 20170804

---

Imperium - FW Death Korps of Krieg.cat

I found the twin heavy stubber in the FAQ.

Fixing #1109 again. For real this time.

---

Chaos - FW Heretic Astartes.cat

Fixes #1112 - Corrected errors in Greater Blight Drone profile
Fixes #1124  - Corrected errors in Hellforged Predator profile

FW HA Fixes 20170805

---

Chaos - FW Renegade and Heretics.cat

have done a bunch of rework, marauders and mutants redone, corrected commander, disciples, command squad and militia

Closes #1132 mutated the mutants and put the rest in line

---

Chaos - Chaos Space Marines.cat
Chaos - Thousand Sons.cat

- Fixes #1138 - Made Berzerker champion weapons work properly.
- Fixed missing profile for Tzaangors.

Chaos fixes 20170807

---

Orks.cat

I've made it so that Grot Tanks always show, but are limited to 0 units unless you have a big mek.  Closes #826
Also Fixed Kaptin Badrukk's Spelling in his profile. Closes #1141

Fix Spelling error, change Grot Tank Constraint

---

Imperium - Blood Angels.cat

Primaris units updated according to Codex Space Marines Errata v1.0.
Closes #1173.

BA Primaris - Codex: Space Marines Errata v1.0

---

Imperium - Grey Knights.cat

Gk codex - Closes #1198 #1201 #1200 #1197

---

Chaos - Chaos Space Marines.cat
Chaos - Daemons.cat
Chaos - Thousand Sons.cat

- Codex: Chaos Space Marines released!
- Index Chaos FAQ 1.2 changes
- Added new Dark Hereticus powers to Thousand Sons.

Chaos Updates

---

Chaos - FW Renegade and Heretics.cat

removed share from filter on rabble added 4 points to militia specialist

closes #1209 Closes #1184

---

Chaos - Chaos Space Marines.cat

Character Validation error

---

Chaos - Chaos Space Marines.cat
Warhammer 40,000 8th Edition.gst

Fixes #1287 - Corrected Chosen weapon validation
Fixes #1281 - Corrected Fallen power fist cost
Fixes #1280 - Fixed Character artefact validation

Chaos Fixes 20170818

---

Imperium - Grey Knights.cat

Closes #1301 #1190

---

Chaos - Chaos Space Marines.cat
Chaos - FW Heretic Astartes.cat
Chaos - Questor Traitoris.cat

Fixes #1299
Fixes #1298
Fixes #1297

Chaos Fixes 20170820

---

Chaos - Chaos Space Marines.cat

Fixes #1320 - Soulreaper validation for Rubrics fixed.

CSM Fixes 20170821

---

Chaos - Thousand Sons.cat

Fixes #1331 - Ahriman (both versions) can now select from Dark Hereticus

Powers for Ahriman

---

Aeldari - Drukhari.cat

Added an optional filter to hide entries other than those with the selected faction keyword(s).
Closes #1203.

Drukhari - Faction Keyword Filter

---

Imperium - Blood Angels.cat

Astorath no longer shows The Sanguinor's profile. Fixes #1358.

BA v20 - Astorath profile fix

---

Chaos - Chaos Space Marines.cat
Chaos - Daemons.cat

- Fixes #1349 - Noise Champion weapon choice updated
- Added new Dark Hereticus powers for Be'lakor

Chaos Fixes 20170825

---

Chaos - Chaos Space Marines.cat

Fix for #1362

---

Aeldari - FW Corsairs.cat
Aeldari - Ynnari.cat

felarch weapon options & Ynnari FW craft

Aeldari Edits

---

Imperium - FW Adeptus Astartes.cat

Added Gabriel Angelos. Closes #1377.

Gabriel Angelos

---

Aeldari - Craftworlds.cat
Aeldari - Ynnari.cat

closes #1397 
closes #1058 <-- once and for all (hopefully!)

A couple of cheeky fixes

---

Chaos - Chaos Space Marines.cat

Added default Plague knife to melee Plague Marine.

Fixes #1407

---

Chaos - Questor Traitoris.cat

Stormspear Rocket pod now has correct profile.

Fixes #1436

---

Imperium - Blood Angels.cat

Added entry for Primaris Captain with Power Fist. References #1408.

BA v21 - Store Anniversary Primaris Captain

---

T'au Empire.cat

Added keyword profiles to all units.
Closes #1375.

Tau Empire - Keywords

---

Imperium - Deathwatch.cat

Add files via upload - Deathwatch V10

---

Chaos - Death Guard.cat

All new units and rules added
Closes #1456

DG codex update

---

Chaos - Death Guard.cat

Minor fixes

---

Chaos - Death Guard.cat
Chaos - FW Heretic Astartes.cat

- Fixes #1489 - Fixed point costs.
- Fixes #1490 - Added new Contagion powers for Necrosius
- Fixed wording in Miasma of Pestilence.

DG Codex Fixes

---

Imperium - Dark Angels.cat

Corrected PL cost  'break' for DA Ravenwing bike squad.

---

Imperium - FW Death Korps of Krieg.cat
Imperium - FW Elysians.cat

Ig improvements

---

Imperium - Questor Imperialis.cat

Updated Thermal Cannon profile according to the new Codex: Adeptus Mechanicus profile.
Updated book and page information for Codex: AdMech knights.
Updated book and page information for Imperial Armour Index: Forces of the Astra Militarum knights.

QI v4 - Codex: AdMech update

---

Chaos - Daemons.cat

Corrected cost of Blue Horrors on Burning Chariot for Herald to match standard chariot

Herald on BC fix

---

Imperium - Adeptus Astra Telepathica.cat
Imperium - Astra Militarum.cat

Various fixes

---

Chaos - FW Heretic Astartes.cat
Chaos - Questor Traitoris.cat

- Updated Thermal Cannon details
- Fixes #1551

FAQ updates and fix

---

Chaos - Death Guard.cat

Deathshrouds can now teleport

---

Imperium - Astra Militarum.cat

Verified points were correct for all Codex entries. Updated "Emergency Plasma Vents" rule text, moved it to Shared Profiles, linked. Added Valkyrie "Roving Gunship" rule. Updated Creed's "Voice of Command" text. Updated Basilisk and Hellhound weapon profiles.

#1589 Points QA and other changes

---

Imperium - Astra Militarum.cat

Didn't catch Emergency Plasma Vents on Pask and the Tank Commander.

#1589 EPV for Pask and TC

---

Imperium - Astra Militarum.cat

Added the Psykers (Primaris, Astropath, Wyrdvane) and removed the shotgun from Officer ranged weapon options

#1589 Psykers, Officers

---

Imperium - Astra Militarum.cat

...except the Valkyrie. Wanted to double-check how to implement before commit.

#1589 Everything under "Exisiting Units"

---

Aeldari - Craftworlds.cat
Aeldari - Harlequins.cat
Aeldari - Ynnari.cat

A few minor updates for our skirt wearing friends...

Monday Fixes

---

Imperium - Astra Militarum.cat

Minus the Priest request, as alphalas pointed out in request.

#1605 All fixes

---

Chaos - Death Guard.cat

Fixes #1600
Added JP Sorc and Lord back in to catalogue with necessary weapon validation amendments

Added Index Jump Pack units

---

Imperium - FW Adeptus Astartes.cat

Sokar Pattern Stormbird Transport profile updated. Fixes #1607.

FWAA v15 - Stormbird bugfix

---

Imperium - Deathwatch.cat

SIA Upgrade

---

Chaos - Death Guard.cat

Slimy Beasts

---

Imperium - Astra Militarum.cat

...what needed to be fixed, anyway.

Fixes #1636

---

Imperium - Astra Militarum.cat

Command Squad HWT

---

Chaos - Chaos Space Marines.cat
Chaos - Death Guard.cat
Chaos - FW Heretic Astartes.cat

Chaos Fixes

---

Imperium - Astra Militarum.cat

Use this one! Doesn't contain conflicts due to my branch being out of date... :(

Fixes #1692 (for real this time)

---

Chaos - FW Renegade and Heretics.cat

R&H rework

---

Aeldari - Craftworlds.cat

Bug tracker update 2

---

Imperium - Deathwatch.cat

Librarius Discipline Updated

---

Chaos - FW Renegade and Heretics.cat

Fixes #1759 and various other LOW issues.

R&H LOW Fixes

---

Aeldari - Craftworlds.cat

Updates Craftworlds to be consistent with the design document flowchart for #1414 
Closes #1765 with updated selection logic.

Craftworlds FAQ and Design Doc Update

---

Imperium - Grey Knights.cat

Typo that almost makes sense: "manifesting of denying" psy powers for "manifesting or denying" psy powers.

Update Imperium - Grey Knights.cat

---

Aeldari - Craftworlds.cat

Reinstated Banshee mask & Mandiblaster options.
Closes #1778

Autarch Skyrunner Equipment

---

Imperium - FW Adeptus Astartes.cat

Astraeus Super-heavy Tank added. Closes #1780.

FWAA v16 - Astraeus Super-heavy Tank

---

Aeldari - Craftworlds.cat

Range reduces from 122 to 12".
Closes #1787

Nova-Lance Nerf

---

Imperium - Deathwatch.cat
Warhammer 40,000 8th Edition.gst

DW & GST weapon cost adjustments

---

Chaos - Thousand Sons.cat

Updated Thousand Sons with costs and other changes from Codex: CSM following the new guidance in the Developer's Commentary.

TS cost updates

---

Imperium - Blood Angels.cat
Warhammer 40,000 8th Edition.gst

Updated BA according to C:SM and FAQs.
Fixed GST typo in Melta Bombs.

Blood Angels rework and GST typo

---

Aeldari - Craftworlds.cat
Imperium - Space Wolves.cat
Orks.cat

several minor bug fixes for long-outstanding bugs...

Various tiny tweaks

---

Orks.cat

I've added the keywords to profile entries so that they show on output (Just like Crafworld cat).  In addition, I've updated the explodes entries to reflect the rules at a glance (Just like Astra Militarum).

Orks Add Keyword

---

Imperium - Adeptus Mechanicus.cat

admech typos

---

Aeldari - Craftworlds.cat

Eldar CA Points Adjustments

---

Aeldari - Craftworlds.cat

CWE Warlord Traits Implementation & Warp Hunter fix

CWE Warlord Traits Implementation

---

Imperium - Adeptus Titanicus.cat
Imperium - Blood Angels.cat
Imperium - FW Adeptus Astartes.cat
Imperium - Legion of the Damned.cat
Imperium - Questor Imperialis.cat

Points updated for BA, FWAA, AT and LotD.

Chapter Approved 2017 points update

---

Imperium - Astra Militarum.cat

Also contains all other CA points updates for Astra Militarum, just committed to the correct branch this time.

Fixes #1826 and CA Points Updates - Astra Militarum

---

Imperium - Adeptus Mechanicus.cat

I couldn't find how to change the Power Fist cost!

AdMech - Chapter Approved Points Costs Changes.

---

Imperium - Space Marines.cat
Warhammer 40,000 8th Edition.gst

This includes some changes to the base `.gst` so review merge carefully.

Chapter Approved updates for Space Marines.

---

Chaos - Chaos Space Marines.cat
Chaos - Daemons.cat
Chaos - Death Guard.cat
Chaos - FW Heretic Astartes.cat
Chaos - FW Renegade and Heretics.cat
Chaos - Questor Traitoris.cat
Chaos - Thousand Sons.cat
Chaos - Titanicus Traitoris.cat

Chapter Approved points updates for all Chaos forces.
Fixes #1831, #1809

Chaos chapter approved updates

---

Orks.cat

This branch has the Ork cat updated with the Chapter Approved points.  I'm going to hold it for a week until the official release date.

Orks Chapter Approved Updates

---

Imperium - Deathwatch.cat

Storm Shield Fix

---

Chaos - Daemons.cat

Updated Nurglings and Plague Drones based on Death Guard Codex

Cost update

---

Imperium - Grey Knights.cat

GK Chapter Approved Pass 1

---

Aeldari - Drukhari.cat
Aeldari - FW Corsairs.cat

Chapter Approved Updates

---

Imperium - Astra Militarum.cat

My bad y'all -- sorry I missed this in the first place.

Fixes #1874

---

Chaos - Chaos Space Marines.cat
Chaos - FW Heretic Astartes.cat

Missed CA updates

---

Chaos - Daemons.cat
Chaos - Death Guard.cat
Chaos - Thousand Sons.cat

Fixes #1883, #1879, also Helbrute changes for TS.

More Chaos CA Updates

---

Imperium - Blood Angels.cat
Imperium - FW Adeptus Astartes.cat
Imperium - Questor Imperialis.cat

Chapter Approved updates for Imperial Knights.
Chapter Approved updates, bugfixes and new units for FW Adeptus Astartes.
Bugfixes for Blood Angels.

CA updates, bugfixes

---

Imperium - FW Death Korps of Krieg.cat

Because when I'm wrong I admit it.

Fixes #1910

---

Imperium - Space Wolves.cat

Changes SW Inceptors to work like Space Marines.  Unfortunately, this refactors the unit and saved lists will not be backward compatible.

Fixed SW Inceptors

---

Aeldari - Harlequins.cat

Harlequin Update

---

Chaos - Thousand Sons.cat
Warhammer 40,000 8th Edition.gst

Fixes #1962, #1924, #1920, #1918

Thousand Sons fixes

---

Chaos - Chaos Space Marines.cat

Fix for #1915

---

Aeldari - Craftworlds.cat

Due to the new release of Battlescribe the bodge job to get keywords to show in roster view has been removed.

Keyword Bodge Gone

---

Chaos - Chaos Space Marines.cat
Chaos - Daemons.cat
Chaos - Death Guard.cat
Chaos - FW Heretic Astartes.cat
Chaos - FW Renegade and Heretics.cat
Chaos - Thousand Sons.cat

**Daemons**
Fixes #1972, #1981
**Thousand Sons**
Fixes #2018
**FW Heretic Astartes**
- Fixes #1984
- Doom Siren profile fixed
**Death Guard**
Fixes #2000 
**Chaos Space Marines**
Fixes #2006 
**FW Renegades and Heretics**
- Fixes #1975
- Updated Leman Russ entry to match Codex Astra Militarum

Chaos fixes 20171211

---

Imperium - Blood Angels.cat

Fixed hand flamer and inferno pistol costs. Fixes #2008, fixes #2009.

BA v28 - Codex update hotfixes

---

Aeldari - Craftworlds.cat
Aeldari - Ynnari.cat

Craftworld Copy & Paste in Ynnari

---

Chaos - Thousand Sons.cat

Category updates

---

Imperium - Dark Angels.cat

No new units here, nor the few rules updates, just the points costs changes.

Dark angels codex points cost changes

---

Aeldari - Craftworlds.cat
Aeldari - Drukhari.cat
Aeldari - Ynnari.cat
Imperium - Deathwatch.cat

Monday Night Fixes

---

Imperium - Deathwatch.cat
Imperium - Space Wolves.cat

More fixes

---

Chaos - FW Heretic Astartes.cat

Xiphon update

---

Imperium - Astra Militarum.cat

Have I mentioned lately that I really despise the whole "But I can taaaaaake it in the Index, you've gotta include it noooooooow" wankery? No? Well, I hate it.

Fixes #2041

---

Imperium - Blood Angels.cat

Chaplain on bike now has his Crozius. Fixes #2050.
Scout sergeant constraints fixed. Fixes #2059.
Frag cannon cost and Blood boil decription corrected. Fixes #2069.

BA v30 - bugfixes

---

Chaos - FW Renegade and Heretics.cat

References:
Chapter Approved 2017 Edition:  page 122 
Please let me know if you would like any changes.

Modified weapon profiles for CA

---

Chaos - Thousand Sons.cat

- Fixes #2018 properly
- Added Warlord Traits

1KSons Updates

---

Imperium - Blood Angels.cat
Imperium - FW Adeptus Astartes.cat

Updated Leviathan weapon description. Closes #2089.
Currently waiting for clarification about #2087, please do not merge yet.

FWAA bugfix, BA bugfixes (safe to merge now)

---

Imperium - FW Death Korps of Krieg.cat

DKOK Quartermaster fix

---

Imperium - Astra Militarum.cat

Sly Marbo typos

---

Orks.cat

Added Squiggoth Weapon

---

Orks.cat

Removed FLY keyword from Boss Snikrot
Added Gorin' Horns weapon to Squiggoth.

Fixed Snikrot and Squiggoth

---

Aeldari - Craftworlds.cat
Imperium - Deathwatch.cat
Warhammer 40,000 8th Edition.gst

Closes a couple of annoying issues that have been open a while 😄

Friday Fixes

---

Aeldari - Harlequins.cat

Harlequin Warlords

---

Imperium - Space Wolves.cat

Grey Hunters fix

---

Imperium - Grey Knights.cat

Lots of derping before herping on this one...things should be better now. I should really do that QoL pass now that I'm out of the hospital.

Closes #2253

---

T'au Empire.cat

Added Warlord Traits and Relic
Closes #1895

Warlord Traits and Relic

---

Chaos - FW Renegade and Heretics.cat

Please let me know if you would like any changes.

Rh designer commentary

---

Chaos - Chaos Space Marines.cat
Chaos - Daemons.cat
Chaos - Thousand Sons.cat

Fixes from Chaos FAQs released on 2018-01-22

Chaos FAQs 20180122

---

Imperium - Blood Angels.cat
Warhammer 40,000 8th Edition.gst

BA v36 - Bugfixes
GST v37 - Fixes Skyspear Missile Launcher cost

BA bugfixes, GST point cost fix

---

Imperium - Adeptus Custodes.cat
Warhammer 40,000 8th Edition.gst

Gentlemen, start cooking your banana pudding!

Custodes Codex!

---

Imperium - Adeptus Custodes.cat

Custodes Bugfixes

---

Imperium - Adeptus Custodes.cat

Custodes Warden Fix

---

Imperium - FW Death Korps of Krieg.cat

Fixes #2268

---

Imperium - Blood Angels.cat
Imperium - Questor Imperialis.cat

BA bugfix.
Corrected relic and warlord validation for BA and QI.

BA fixes, BA and QI validation

---

Imperium - Astra Militarum.cat

Including the actual fix in the commit this time...sheesh

Fixes #2377

---

Chaos - Thousand Sons.cat
Warhammer 40,000 8th Edition.gst

Thousand Sons Codex release
- Daemons are not included. You will need to use a multi-faction detachment if you really want to put Daemons in your Thousand Sons detachment.

DO NOT MERGE - Thousand Sons Codex

---

Imperium - FW Adeptus Astartes.cat

New layout for Lev Dread

---

Imperium - Blood Angels.cat

Corrected validation on Captain's bolt pistol. Corrected psychic powers. Fixes #2413.

BA bugfixes

---

Imperium - Blood Angels.cat

Fixed inconsistencies and typos in the psychic powers. Closes #2458.

BA v39 - bugfix

---

Imperium - Adeptus Custodes.cat
Imperium - Astra Militarum.cat

Restricts cadian/catachan/non-tempestus when specific regiments selected.

AM Doctrine Unit Selection

---

Imperium - Inquisition.cat

Added Inquisitor Eisenhorn

---

Imperium - Adeptus Ministorum.cat

Added missing Damage stat in 'Blade of Admonition' Adepta Sororitas Relic

Added missing stat in Adeptus Ministorum Relic

---

Imperium - Grey Knights.cat

Grey Knight fixes - closes #2515 and closes #2470

---

Aeldari - FW Corsairs.cat
Aeldari - Ynnari.cat

Friday Night Tweaks

---

Imperium - FW Elysians.cat

Also fixes Drop Troopers with krak grenades madness

Fixes #2658

---

Imperium - Blood Angels.cat

Chaplains can now equip their power fists freely. Fixes #2621.
Land Speeder Storm now has all weapons. Fixes #2635.

BA v41 - bugfixes

---

Imperium - FW Death Korps of Krieg.cat
Orks.cat

- Cleaned up hades drill squad, and sgt options.
- Created local entries for plasma + bolt pistols and replaced throughout codex. (Cost was wrong in .gst)
- Added minimum 1 too heavy weapon team's heavy weapon
- Updated master of ballistics rule to codex version

Fix/FW Death Korp

---

Warhammer 40,000 8th Edition.gst

For Warlord validation across Aeldari catalogues

Ynnari GST Flag

---

Orks.cat

Updates Biker Boss Waaagh!
And Update Mob Rule

Ork FAQ Updates

---

Imperium - FW Adeptus Astartes.cat
Warhammer 40,000 8th Edition.gst

Fixed some point costs in GST and updated FWAA according to April 2018 Big FAQ.

GST Fixes and Big FAQ

---

Aeldari - Drukhari.cat

Drukhari Fixes

---

Orks.cat

Closes #2917
Closes #3031
Updates #2932

Ork Forgeworld FAQ Updates

---

Imperium - Deathwatch.cat

~~close #3149 #3139 #3138 #3131~~
fix #3149, fix #3139, fix #3138, fix #3131
*edit by amis92*: cause: https://help.github.com/articles/closing-issues-using-keywords/#closing-multiple-issues

Deathwatch bug fixes

---

Imperium - Deathwatch.cat

Intercessor SIA Update

---

Imperium - Space Marines.cat

- Named characters now have correct Traits
- Standard traits redesigned
- Trait visibility fixed
Fixes #3016

SM Trait Fixes

---

Imperium - Deathwatch.cat

FAQ adjustments

---

Aeldari - Harlequins.cat
Imperium - Deathwatch.cat

Simple Fixes

---

Warhammer 40,000 8th Edition.gst

It came from the warp to closes #3205

Webway Gate Update

---

Chaos - Questor Traitoris.cat

- Added Knight Dominus and Armigers
- Added QT Super-heavy detachment
- Added Relic and Warlord Traits and supporting options for all units.

Index - Renegade Knights

---

Imperium - Deathwatch.cat

Overzealous Chaplain

---

Imperium - Space Marines.cat

SM Fixes 20180725

---

Imperium - Deathwatch.cat

Watch this!

---

Imperium - FW Elysians.cat

Fixes #3477 
Removed all WL Traits min1 constraints.
Created local Warlord entry and relinked as needed.
Tidied up Show/Hide modifiers

Elysian Trait FIx

---

Chaos - Death Guard.cat

Fix typo in "Suppurating Plate" Description field

---

Chaos - Gellerpox Infected.cat

Initial version of Gellerpox catalogue

Initial Commit

---

Imperium - Elucidian Starstriders.cat

Euclidean Skywalkers - Initial Version

---

Aeldari - Craftworlds.cat

a little quick fix

---

Imperium - Space Marines.cat

Fixes #3590 
Fixes #3595 
This update will break lists which contain Relics.

SM Relic rework

---

Chaos - Chaos Space Marines.cat

This PR adds a missing space in the value attribute.

Fix typo in "For the Dark Gods" description

---

Imperium - Blood Angels.cat

Rhino no longer linked to Razorback attributes.

Update Imperium - Blood Angels.cat

---

Orks.cat

This should bring the Ork Cat up to date with the 8th edition codex.

Ork codex wip

---

Orks.cat

Fix Megatrukk Scrapjet points cost

---

Orks.cat

Update Typos, add some index options

---

Orks.cat

Fix points on Mek Gunz

---

Orks.cat

Fix Warlord Traits

---

Orks.cat

Now you can take an extra warlord trait, and I fixed the orky spelling.
Closes #3839

Update Morgargs Finkin' Cap

---

Orks.cat

You can now select a warlord trait under the relic.  That allows you to have 2 warlord traits on the same model.  It is also validating to make sure that you don't take the same WL trait twice.   
Closes #3839

Fix Morgargs Finkin' Cap

---

Orks.cat

Closes #3866
Closes #3867
Closes #3868

Tweak a few points, and constraints

---

Imperium - Adeptus Mechanicus.cat

- removed superfluous entry group

---

Imperium - Astra Militarum.cat

Revert "Final Points Pass for CA2018"

---

Aeldari - Craftworlds.cat

Fixes the costing for wraithknight weapons (Scattershield and Suncannon changes)

Fixes #4016

---

Imperium - Astra Militarum.cat

Revert "Fixes #4211"

---

Imperium - Astra Militarum.cat

Revert "Fixes #4221"

---

Aeldari - Drukhari.cat

Update Aeldari - Drukhari.cat

---

Aeldari - Craftworlds.cat

Update Aeldari - Craftworlds.cat

---

Aeldari - Harlequins.cat

Update Aeldari - Harlequins.cat

---

Imperium - Blood Angels.cat

The change in line 15712 wasn't made by me but rather by just saving the cat file.

Fix Cpt. Tycho's wound characteristics, add book and page, close #4411

---

Warhammer 40,000 8th Edition.gst

Removes mandatory selection of CP choices.

CP Handling Updated

---

Imperium - Space Wolves.cat

Constraints were missing "and child items" flag.
Also modified the Trophies of Fenris selector so that you can only choose one of the options (and only select them once)

Fixes #4664

---

Aeldari - Craftworlds.cat

Field Commanders Permitted

---

Imperium - Grey Knights.cat

Pre Game Enforcement flag for GK

---

Chaos - Chaos Space Marines.cat

Shadowspear chaos

---

Imperium - Space Marines.cat

Shadowspear Space Marine Stuff

Sm shadowspear

---

Imperium - Blood Angels.cat
Imperium - Dark Angels.cat
Imperium - Space Marines.cat

Spees Muhreens

---

Imperium - Dark Angels.cat

- PL of Infiltrators
- mention #4900

Dark Angels

---

Orks.cat

Closes #5081
Closes #5079
Closes #5064
Closes #5048

Typos, and Nob Bikers

---

Chaos - Daemons.cat

- Updated Keeper
- Added Shalaxi
- Added Contorted Epitome
- Added Syl'esske

Slaanesh updates

---

T'au Empire.cat

T'au Empire FAQ/Errata April 2019 and references cleanup

---

Aeldari - Craftworlds.cat
Aeldari - Drukhari.cat
Chaos - Chaos Space Marines.cat
Chaos - FW Heretic Astartes.cat
Chaos - FW Renegade and Heretics.cat
Chaos - Servants of the Abyss.cat
Imperium - Adeptus Custodes.cat
Imperium - Astra Militarum.cat
Imperium - Blood Angels.cat
Imperium - Deathwatch.cat
Imperium - FW Adeptus Astartes.cat
Imperium - Space Wolves.cat
T'au Empire.cat

3rd attempt at fixing #5204
Previous attempts: #5205, #5213

Fixing fatal merge - see #5204

---

Imperium - Dark Angels.cat
Imperium - FW Adeptus Astartes.cat

- added AIRCRAFT keyword
mention #5220

FW AA & DA Aircraft keyword

---

Imperium - Adeptus Mechanicus.cat

adding new skitarii vehicles

---

Imperium - Space Wolves.cat

Fixes #5354 Add Repulsor Executioner

---

Imperium - Space Wolves.cat

Changed everything that was changed in the August 2019 errata for the space wolves file only. Hasn't changed things in Space Marines File.

SPACE MARINES ERRATA - August 2019 - Space Wolves changes

---

Chaos - Chaos Space Marines.cat
Chaos - Death Guard.cat
Chaos - FW Heretic Astartes.cat
Chaos - Thousand Sons.cat

Added 'Hateful Assault'

---

Orks.cat

Sent a mekboy ta fix 'da trukk transport kapacity an' 'da rukkatrukk squigbuggy's squig launcha. 'e fixed both but 'ploded on squig mine on da way back.

Orks - Fixes for Truck and Rukkatrukk Squigbuggy

---

Orks.cat

Thought tankbustas how ta make tanks 'plode betta

Fixed Ork's Tank Hunter ability

---

Imperium - Blood Angels.cat
Imperium - Dark Angels.cat
Imperium - Deathwatch.cat
Imperium - FW Adeptus Astartes.cat
Imperium - Space Marines.cat
Imperium - Space Wolves.cat

Removed FW "Warlord" entry and replaced with the local one in all cases.

Chaplain Dread fix

---

Chaos - Chaos Space Marines.cat
Chaos - Death Guard.cat
Chaos - FW Heretic Astartes.cat
Chaos - Thousand Sons.cat

Merged all FW models into main Chaos catalogues.

Chaos FW Merge

---

Aeldari - Craftworlds.cat
Aeldari - Drukhari.cat
Aeldari - Harlequins.cat
Aeldari - Ynnari.cat

Rework of Ynnari Relics to respect weapon choices where necessary.

Fixes #5629

---

Chaos - Chaos Space Marines.cat
Chaos - Daemons.cat
Chaos - Death Guard.cat

Title; minor Death Guard Warptime typo fix that led to discovering the same typo in the Daemons entry

typo in two Warptime entries: ',pre' -> 'more'

---

Orks.cat

Fixed CP values for Ork Boyz not being calculated

---

Orks.cat

Issue was introduced in PR #6036 (Sorry!)
Fixes issue #6043

Ork Boyz upgrade deduce CP instead of adding it

---

Imperium - Astra Militarum.cat

Includes updates for both Codex and FW units

Astra Militarum MFM 2019 Points Update

---

Imperium - Astra Militarum.cat

Revert "Astra Militarum MFM 2019 Points Update"

---

Orks.cat

Orks check off #6086
Orks Check off #6079

Update Orks for Munitorum Field Manual and Legends

---

Imperium - Inquisition.cat

I've updated the points based on the latest Munitorum Field Manual.
There was only one change.

Inquisition Points Update

---

Chaos - Death Guard.cat

Updated points for Chaos- Deathguard entries per the chapter approved 2019 updates

MFM2019 - Deathguard

---

Imperium - Sisters of Silence.cat

Executioner Greatblades -> 5pts
Storm Bolters -> 2pts
Hunter-Killer Missile -> 6pts
(accidental delete of old pull request when cleanign up commits from other codexes)

Update Imperium - Sisters of Silence.cat

---

Imperium - Officio Assassinorum.cat

Points updates officio Assasinorum (tidied up commits and mixed files)
all assasins up 10 pts

Update Imperium - Officio Assassinorum.cat

---

Imperium - Inquisition.cat

Legends name switching to "Inquisitor [Legends]" for Inquisitors with Null Rod
Null rod renamed to "Null Rod [Legends]"

Update Imperium - Inquisition.cat

---

Imperium - Adeptus Custodes.cat
Imperium - Grey Knights.cat

Closes #6118

---

Imperium - Space Marines.cat

champion of fist fixer

---

Imperium - Space Marines.cat

Closes #6403
closes #6009
closes #6287
closes #6370
closes #6345

Fly the Friendly Skies

---

Imperium - Astra Militarum.cat
Imperium - FW Death Korps of Krieg.cat

Fixes this for both DKoK and AM datafiles.

Closes #6464

---

Imperium - Space Marines.cat

Legend..... wait for it.... dary

---

Imperium - Space Marines.cat

closes #6539
closes #6526
closes #6518
closes #6516

Bugs? What bugs?

---

Chaos - Thousand Sons.cat

#6594
- Added Cult selector and all Cult content (powers, WLTs and Relics)
- Magister added to all relevant models.
- Exalted Mutation modifiers added to all relevant models.

Thousand Sons Ritual of the Damned content

---

Imperium - Space Marines.cat

Update Imperium - Space Marines.cat

---

Orks.cat

I've added in the new options from Saga of the Beast, and fixed a couple of bugs.
Closes #6910
Closes #6908
Closes #6911
Updates #6764

Add in Saga of the Beast

---

Orks.cat

I fixed the way Kustom Jobs work, and updated the new datasheets.
Closes #6952
Closes #6953
Closes #6951
Closes #6954
Updates #6764

Updating Ork Constraints.

---

Orks.cat

Closes #6969
Closes #6967
Closes #6964
Closes #6958
Updates #6764

A Few More Cleanups for Kustom Jobs

---

Orks.cat

Closes #6988
Updates #6990
Closes #6991
Closes #6992
Closes #6989

Ork Bug Fixes

---

Imperium - Black Templars.cat
Imperium - FW Adeptus Astartes.cat
Imperium - Imperial Fists.cat
Imperium - Iron Hands.cat
Imperium - Raven Guard.cat
Imperium - Salamanders.cat
Imperium - Space Marines.cat
Imperium - Ultramarines.cat
Imperium - White_Scars.cat

I broke all the sm lists

---

Chaos - Questor Traitoris.cat

Chaos Knights - Engine War

---

Chaos - Death Guard.cat

- Plague Companies
- New Relics
- New WLTs
- New Stratagems

War of the Spider updates for Death Guard
