Imperium - Blood Angels.cat

Both versions of Tycho now have the keyword Tycho.
Removed collective gear from Sanguinary Ancient. Fixes #686.
Techmarine servo-arm options reworked. Fixes #687.
Rhino now has its defaul storm bolter. Fixes #690.
Scout Sergeant doesn't have access to heavy weapons anymore. Fixes #691.
Sternguard Veteran Sergeant options reworked. Fixes #689.

BA v12 - bugfixes

---

Imperium - Inquisition.cat

Quad Heavy Bolter was 72pts should be 36pts.
Changed Quad Heavy Bolter to 36pts a piece.

Quad Heavy Bolter point adjustment.

---

Imperium - Blood Angels.cat
Imperium - FW Adeptus Astartes.cat

FWAA v6
Added missing weapons to Relic Leviathan Dreadnought. Fixes #754.
Added Relic validation rules.
Added psychic powers.
BA v13
Fixed Devastator Sergeant weapon options. Fixes #735.

BA bugfixes, FWAA improvements and bugfixes

---

Chaos - Death Guard.cat
Chaos - Thousand Sons.cat

After starting fresh, I noticed V9 doesn't contain all the info needed to make Sorcerer on Palanquin of Nurgle available in the Death Guard List.  I've created the missing info.
This Fixes #703 and #704 they have been closed but should be re-opened and resolved.
See comment below -- also Fixes #762 and #763

Added Sorcerer on Palanquin of Nurgle to Death Guard Army List and change Smoke Launchers to point to Smoke Launchers

---

Imperium - Astra Militarum.cat

Shadowsword's Volcano Cannon are 2D6 not D3 (see p35 and p146 in I:I2)

Bugfix: Shadowsword's Volcano Cannon are 2D6 not D3

---

Imperium - Astra Militarum.cat

Changed default weapon in a Company Commander's chainsword hand from noting to a chainsword (like in the index).
This is to avoid the error: "Company Commander must have 1 more selections from Chainsword (minimum 1)" when adding a Company Commander

bugfix:AM Set a default for a Company Commander's chainsword hand

---

Chaos - Chaos Space Marines.cat
Chaos - Death Guard.cat
Chaos - FW Heretic Astartes.cat
Chaos - Thousand Sons.cat

- Updated profile for Chaos Cultists to auto-include extra attack for brutal assault weapon
- Deathguard refactor (rules -> profiles, unit re-implementation where needed [BREAKING CHANGE], spell check of rules, added psychic power pick lists)
- Thousand Sons refactor (rules -> profiles, unit re-implementation where needed [BREAKING CHANGE], spell check of rules, added psychic power pick lists)
- CSM refactor (rules -> profiles, unit re-implementation where needed [BREAKING CHANGE], spell check of rules, added psychic power pick lists)
- FW Heretic Astartes FAQ 1.1 changes. Fixes #810 
- Fixes #825 
- Fixes #841

Chaos updates

---

Chaos - Death Guard.cat

Fixes for #906 
- Chaos Lords can now take 2 pistols.
- Cultists reimplemented, copied from Chaos Space Marines
- Missing constraints for grenades and Smite fixed on various units.
- Helbrute auto-increment of attacks if two melee weapons.

Death Guard fixes

---

Chaos - Chaos Space Marines.cat
Chaos - Daemons.cat
Chaos - FW Heretic Astartes.cat

Fixes #966 - Added Infernal Hunger to Scorpius
Fixes #969 - Removed Staff of Change option
Fixes #972 - Corrected statline
Fixes #973 - Removed duplicate Psyker profile
Fixes #978 - Added Strength to Butcher cannon
Fixes #980 - FIxed Plasma zerker being an upgrade.

Chaos Fixes

---

Chaos - Chaos Space Marines.cat

Improves Relic validation. 
It will now not allow the selection of a relic weapon if the relevant base weapon has not been selected. Also fixed a couple of bugs in relic eligibility.

CSM Relic Validation

---

Imperium - FW Elysians.cat

At least in my copy, current version is incorrectly costing at 27 total, which I believe is due to it assuming the THB costs 17, not 14.

Fix THB cost for Tarantula turrets.

---

Imperium - Adeptus Titanicus.cat
Imperium - Blood Angels.cat
Imperium - Legion of the Damned.cat
Imperium - Questor Imperialis.cat

Updated Questor Imperialis according to Codex: Adeptus Mechanicus (adding Questor Imperialis/Questor Mechanicus selector, which only changes keywords, to Knights Crusader, Errant, Gallant, Paladin and Warden).
Removed HTML sequences (which were not showing correctly) from Adeptus Titanicus, Blood Angels and Questor Imperialis.
Added keyword display to Adeptus Titanicus, Legion of the Damned and Questor Imperialis.

Slight improvements, Knights update

---

Chaos - Chaos Space Marines.cat

I was glancing over this rule today and noticed a typo, so I added a missing word.

Fix/Chaos Space Marines Hellbrute Crazed rule

---

Chaos - Chaos Space Marines.cat

Fixes the cost of Doom Siren to it's Chapter Approved 2017 value.

Fix points cost of Doom Siren for Noise Champion to Chapter Approved cost (10 points)

---

Chaos - Death Guard.cat

Addresses Issues #1995 & #2017
I went back and forth a couple times wondering if Daemon Prince and Sorcerer, since used in multiple codexes, should be in Warhammer 40,000 8th instead; but after noticing Daemon Engine and so on were not in base I moved them back to Death Guard.
Updated Categories (otherwise known as Keywords)
* ### Added
* Daemon Prince
* Malignant Plaguecaster
* Sorcerer
* Typhus
- ### Chaos Lord with Jump Pack
- **Categories**
- Added - Heretic Astartes
- ### Daemon Prince of Nurgle
- **Categories**
- Added - Daemon Prince
- Removed - Psyker   --- not listed in Keywords but could be required because of something else
- ### Lord of Contagion
- **Categories**
- Added - Lord Of Contagion
- Removed - Psyker
- ### Malignant Plaguecaster
- **Categories**
- Added - Malignant …

Chaos - Keyword Updates via Categories - HQ & Troops

---

Imperium - Blood Angels.cat

Replaced all wargear entries with links from GST (where appropriate and available).
Updated all datasheets (including points) according to Codex.
New datasheets added.
Warlord traits added.
Psychic powers added.
Relics added.

BA v27 - Codex update

---

Aeldari - Drukhari.cat

Some small updates to get the Drukhari current with Chapter Approved.  Overall changes are:
-Making Warlord 0-1 for all HQs.
-Getting Blood Dancer to appear for Succubus and Lelith
-Getting Master Regenesist to appear for Urien.
-Adding a relic option for the non-special HQs (future relics can be linked to the group)
-Correcting the cost of the Tantalus.

Drukhari Update

---

Imperium - Blood Angels.cat

Redemptor Dreadnought can now unequip its Icarus rocket pod. Fixes #2075.

BA v31 - Redemptor Dreadnought fix

---

Tyranids - Genestealer Cults.cat
Tyranids.cat
Warhammer 40,000 8th Edition.gst

Allows complete relic validation in rosters using multiple factions, as per #2318.

Warlord Validation

---

Imperium - Blood Angels.cat

Typo(Tactical Precision): CLOOD ANGELS -> BLOOD ANGELS
Added(Force Rules): Defenders of Humanity, The Red Thirst

Blood Angels: Typo and Force Rules Added

---

Orks.cat

I added a mandatory Upgrade to Grot Tanks that explains they require a big mek.   Closes #2881
Added explosions to attlewagon w/ Supa-Kannon  Closes #2755

Add a note to Grot tanks to explain constraints

---

Aeldari - Craftworlds.cat

Fixes #3987 - removes base cost from the Selection Entry (as it causes double counting) and changes the inc cost to 15 for Wraithcannon, and 20 for D-Scythe in the selection entry group.

Fix Wraithguard in CA

---

Imperium - Space Wolves.cat

Changed everything that was changed in the August 2019 errata for the space wolves file only. Hasn't changed things in Space Marines File.
Added Shock Assault and Bolter Discipline to the shared rules part.
Added Impulsor, Incursor Squad and Invictor Tactical Warsuit.

Added new rules, changes and units for space wolves

---

Imperium - Space Wolves.cat
Orks.cat

Gave Invictor Tactical Warsuit the right weapon
Removed Termite Assault Drill (Has been replaced with Terrax-Pattern Termite Assault Drill)
Adjusted the Eliminators to the August 2019 Errata
Changed the number of attacks on Aggressor
Fixed Wolf Guard in Tartaros Power Level and default choices
Orks - Fixed Warboss seen as uncategorize
Related issues #5498 #5492 #5401 #5496

Space Wolves - Invictor, Termite Assault Drill Eliminators, Aggressors and Tartaros \ Orks - Warboss fix

---

Orks.cat

The "grot orderly" was referred to as a "grot oiler" at the end of his blurb

corrected grot orderly typo
